name: ModernVillagerShop
version: "${version}"
main: me.f0reach.vshop.ModernVillagerShopPlugin
api-version: "1.21"
authors: [f0reachARR]
description: VillagerShop for 1.21.8+ Minecraft

dependencies:
    server:
        Vault:
            load: BEFORE
            required: true
        BedrockDialog:
            load: BEFORE
            required: true
        PlaceholderAPI:
            load: BEFORE
            required: false
